name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build "guessing_game_1" for Ubuntu
      run: cargo build --bin guessing_game_1 --verbose --release
    - name: Build "guessing_game_2" for Ubuntu
      run: cargo build --bin guessing_game_2 --verbose --release
    - name: Zip both Ubuntu builds together
      run: zip -j target/release/guessing_games_ubuntu.zip target/release/guessing_game_1 target/release/guessing_game_2
    - uses: actions/upload-artifact@v4
      with:
        name: guessing_games_ubuntu.zip
        path: target/release/guessing_games_ubuntu.zip
  
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build "guessing_game_1" for MacOS
      run: cargo build --bin guessing_game_1 --verbose --release
    - name: Build "guessing_game_2" for MacOS
      run: cargo build --bin guessing_game_2 --verbose --release
    - name: Zip both MacOS builds together
      run: zip -j target/release/guessing_games_macos.zip target/release/guessing_game_1 target/release/guessing_game_2
    - uses: actions/upload-artifact@v4
      with:
        name: guessing_games_macos.zip
        path: target/release/guessing_games_macos.zip

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build "guessing_game_1" for Windows
      run: cargo build --bin guessing_game_1 --verbose --release
    - name: Build "guessing_game_2" for Windows
      run: cargo build --bin guessing_game_2 --verbose --release
    - name: Zip both Windows builds together
      run: Compress-Archive -Path target/release/guessing_game_1.exe, target/release/guessing_game_2.exe -DestinationPath target/release/guessing_games_windows.zip
    - uses: actions/upload-artifact@v4
      with:
        name: guessing_games_windows.zip
        path: target/release/guessing_games_windows.zip
  
  create-release:
    needs: [build-ubuntu, build-macos, build-windows] # Ensures release job runs after build jobs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (ubuntu)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/guessing_games_ubuntu.zip
          asset_name: guessing_games_ubuntu.zip
          asset_content_type: application/zip
      
      - name: Upload Release Asset (MacOS)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/guessing_games_macos.zip
          asset_name: guessing_games_macos.zip
          asset_content_type: application/zip
      
      - name: Upload Release Asset (Windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/guessing_games_windows.zip
          asset_name: guessing_games_windows.zip
          asset_content_type: application/zip
